// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYn3M6yMkOyj_Wf3C-oXh_7TVy_mLdRE',
    appId: '1:809423714686:web:398de691e52a85b0131b2f',
    messagingSenderId: '809423714686',
    projectId: 'flutter-chat-app-f7eae',
    authDomain: 'flutter-chat-app-f7eae.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f7eae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrCASQzkktbD8dNnjw47S2I35KOii178',
    appId: '1:809423714686:android:342ce7b013a5cd1a131b2f',
    messagingSenderId: '809423714686',
    projectId: 'flutter-chat-app-f7eae',
    storageBucket: 'flutter-chat-app-f7eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPjAKZQt8bOAgF4icBoDlG4O5b9rEbsow',
    appId: '1:809423714686:ios:108b2b5ec4869ff1131b2f',
    messagingSenderId: '809423714686',
    projectId: 'flutter-chat-app-f7eae',
    storageBucket: 'flutter-chat-app-f7eae.appspot.com',
    iosBundleId: 'com.shreyas.chatApp',
  );

}